### ISSUE TITLE
Could not load file or assembly 'System.Text.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.

### ISSUE THREAD

**Issue by thomaspb88** [neon-sunset/Pinecone.NET#72] opened 2023-11-03 14:07 UTC
Hello, thank you for making this package. It's exactly what I was looking for.

I'm currently developing an Azure Function in .NET 6 and I'm experiencing a System.IO.FileNotFound exception when using this library. I can see the library has dependency on System.Text.Json and System.Net.Http.Json 8.0.0.

I've added the exact same libraries to all of the projects within the solution and still get the same System.IO.FileNotFound exception

Stack Trace

   at Pinecone.PineconeClient.<GetIndex>d__7`1.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Pinecone.PineconeClient.GetIndex[TTransport](IndexName name)
   at Pinecone.PineconeClient.GetIndex(IndexName name)
   at Pinecone.Services.PineconeUpsertService.<Upsert>d__2.MoveNext() in C:\Users\Tom\source\repos\xxxxxxxx\Pinecone.Services\PineconeUpsertService.cs:line 21
   at DocumentIngestionService.IngestionFunction.<Run>d__2.MoveNext() in C:\Users\Tom\source\repos\xxxxxxxx\DocumentIngestionService\IngestionFunction.cs:line 55

**Comment by neon-sunset** [comment] 2023-11-03 14:37
Hi Thomas,

You don't need to explicitly reference transitive dependencies of the library - adding them manually in csproj is not required.
Do you get any warnings when building the project?

**Comment by thomaspb88** [comment] 2023-11-03 16:08
Thank you for responding so quickly. No warnings from building the project.

I've had success using the library within a .NET 6 Console Application however not in an Azure Functions app.

To replicate the issue: Create new Azure Functions app, Install latest version of Pinecone.NET, function as follows:

`using Microsoft.AspNetCore.Http;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.Http;
using Microsoft.Extensions.Logging;
using Pinecone;
using System.Threading.Tasks;

namespace FunctionApp1
{
    public static class Function1
    {
        [FunctionName("Function1")]
        public static async Task Run(
            [HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)] HttpRequest req,
            ILogger log)
        {
            log.LogInformation("C# HTTP trigger function processed a request.");

            using var pinecone = new PineconeClient("58596d7e-2b1c-49f0-be72-862e7156459b", "gcp-starter");

            var pinconeIndex = await pinecone.GetIndex("ai-documentlibrary-index");
        }
    }
}`

Now hit run and trigger the function. The exception is thrown when we reach the GetIndex method.

**Comment by neon-sunset** [comment] 2023-11-03 16:44
Strangely enough, I'm unable to locally reproduce the problem with `net6.0` with standard Azure Function template locally:
```xml
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.19.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.13" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.15.1" />
    <PackageReference Include="Pinecone.NET" Version="1.3.0" />
  </ItemGroup>
```
```C#
[Function("HttpExample")]
public async Task<HttpResponseData> Run(
    [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post")] HttpRequestData req)
{
    using var pinecone = new PineconeClient("api-ket", "env");
    var indexes = await pinecone.ListIndexes();

    if (!indexes.Contains("test-index"))
    {
        await pinecone.CreateIndex("test-index", 1536, Metric.Cosine);
    }

    using var index = await pinecone.GetIndex("test-index");
    _logger.LogInformation($"Index: {index}");

    var upserted = await index.Upsert(new[]
    {
        new Vector { Id = "test-vector", Values = new float[1536] }
    });
    _logger.LogInformation($"Upserted: {upserted}");
    _logger.LogInformation("C# HTTP trigger function processed a request.");

    var response = req.CreateResponse(HttpStatusCode.OK);
    response.Headers.Add("Content-Type", "text/plain; charset=utf-8");
    response.WriteString("Welcome to Azure Functions!");

    return response;
}
```

No warnings are produced and it works as is, with index being both `GrpcTransport` and `RestTransport`-typed (excluding the possibility that the function host itself using gRPC transport may be interacting with the newer version of the dependency).

My suggestion would be to clean `bin`, `obj` folders and installing latest SDK. Let me know if it works.

**Comment by thomaspb88** [comment] 2023-11-06 09:22
Hello again,

Can to give you further feedback to the bug I'm experiencing with Pinecone.NET - I've had some success! After noticing you were running an isolated function, I've just created an isolated function using .NET 6 and installed Pinecone.NET 1.3.0 and no longer get the System.IO.FileNotFound exception.

I would ideally like to no use isolated functions as that will mean I need to use a premium subscription to host of Azure.

**Comment by neon-sunset** [comment] 2023-11-06 09:47
Is there a way for me to test in-process function locally?

I'm assuming that it might be using some kind of custom flavour of dynamic assembly loading and either restricts newer-than-current-LTS dependencies in general, or it's an issue because this library needs RC.1 JSON dependencies from .NET 8.

Regardless, since in-process hosting uses latest LTS version, it may become possible to target .NET 8 soon since it's scheduled for release in the middle of this month.

**Comment by neon-sunset** [comment] 2023-11-12 04:06
@thomaspb88 Closing the issue because I assume the problem has been solved on your end or is no longer relevant. Feel free to reopen if necessary :)

**Closed by neon-sunset** 2023-11-12 04:06 UTC
Labels: question
