### ISSUE TITLE
Can't create a MetdataValue from an object

### ISSUE THREAD

**Issue by nielsbosma** [neon-sunset/Pinecone.NET#97] opened 2024-02-22 14:10 UTC
I'm converting a Dictionary<string, object> metadata to a MetadataMap. There's no way from what I can see to directly create a MetadataValue from an object as the constructor is set to internal. Now I'm forced to do this:

```
private MetadataMap Convert(Dictionary<string, object> metadata)
    {
        var metadataMap = new MetadataMap();
        foreach (var (key, value) in metadata)
        {
            if (value is string stringValue)
            {
                metadataMap[key] = stringValue;
            }
            else if (value is int intValue)
            {
                metadataMap[key] = intValue;
            }
            
            //and so on... 
                
        }
        return metadataMap;
    }
```

**Comment by neon-sunset** [comment] 2024-02-22 21:07
`MetadataValue` being an object internally is an implementation detail mostly caused by C# not having first-class discriminated unions. Exposing it publicly would lead to all kinds of issues - Pinecone supports only a limited set of types there where, for example, numbers have to be normalized to `double`. This means that users passing an object would have no way of knowing if their code is correct or get confused when they write `metadataMap[key] = new(42)` and it doesn't work or all kinds of object types would have to be resolved internally at runtime which is a requirement for serialization and is not practical.

If you can't simply replace `object` with `MetadataValue` in your code, the above example can be written in a terser way:
```cs
map[key] = value switch
{
    int i => i,
    string s => s,
    float f => f,
    ...,
    _ => throw new ArgumentException()
};
```
You will have to decide which specific types the `object` is allowed to be and how they should be converted if `MetadataValue` is not compatible with them.

**Comment by neon-sunset** [comment] 2024-02-26 03:04
Should you have any other questions, feel free to open a new issue or start a new discussion.

**Closed as completed by neon-sunset** 2024-02-26 03:04 UTC
